version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - cd ./client
      - npm install
      - npm run build
      - cd ..
      - npm install
      - npm run build
artifacts:
  files:
    - "./**/**"
